
name: Build

on: [push, workflow_dispatch]

jobs:
  vcpkg-on-linux:

    runs-on: ${{ matrix.os }}
    env:
      CC: gcc-${{ matrix.compiler_version }}
      CXX: g++-${{ matrix.compiler_version }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        compiler_version: [11]

    steps:
      - uses: actions/checkout@v3

      - name: Configure and build
        run: |
          cmake . -B build -DCI_TEST_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release
          cmake --build build

      - name: Test
        run: |
          cd build/tests
          ctest --output-on-failure


  vcpkg-on-windows:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022]

    steps:
      - uses: actions/checkout@v3

      - name: Configure and build
        run: |
          cmake . -A x64 -B build -DCI_TEST_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE="Release"
          cmake --build build --config Release

      - name: Test
        run: |
          cd build/tests
          ctest -C Release --output-on-failure


  vcpkg-on-darwin:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-12]

    steps:
      - uses: actions/checkout@v3

      - name: Configure and build
        run: |
          cmake . -B build -DCI_TEST_BUILD_TESTS=OFF -DCMAKE_BUILD_TYPE="Release"
          cmake --build build